apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gzlc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gzlc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0024-app
  name: devfile-sample-gzlc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gzlc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gzlc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-gzlc@sha256:33f24f5f8b52d72c8bfe8a5e257d3d4c1a0b8e40867f6ea0240d1ef855074315
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
